#ifndef _CAN_NODE_INFO_H_
#define _CAN_NODE_INFO_H_

typedef enum eHydraulicCommand{
    MSG_SYRINGE_APIRATE_DISPENSE_SUCK = 0x04,
    MSG_CRU_DETERGENT_DISPENSE_PUMP_ON_OFF = 0x07,
    MSG_CRU_BIO_HAZARD_SUCTION_PUMP_ON_OFF = 0x09,
    MSG_CRU_OVERFLOW_SUTCION_VALVE_OPEN_CLOSE = 0x0B,
    MSG_ARM_PROBE_CLEANER_VALVE_OPEN_CLOSE = 0x0D,
    MSG_ARM_THROUGH_VALVE_OPEN_CLOSE = 0x0F,
    MSG_CRU_WATER_DISPENSE_VALVE_OPEN_CLOSE = 0x11,
};

typedef enum eRCTCommand{
    MSG_RCT_TRAY_INITIALIZE = 0X01,
    MSG_RCT_TRAY_MOVE = 0X13
};

typedef enum eCRUCommand{
    MGS_CRU_INITIALIZE = 0X08,
    MSG_INTER_UP = 0X09,
    MSG_CRU_DOWN = 0X0A,
    MSG_CRU_RUN_CHECK = 0X12,
    MSG_CRU_MOVE = 0X10
};

typedef enum ePeltierCommand{
    MSG_PELTIER_ENABLE_DISABLE = 0x01,
    MSG_PELTIER_AUTOMATIC_MANUAL = 0x02
};

#endif // _CAN_NODE_INFO_H_